### ISSUE TITLE
8.0不支持 

### ISSUE THREAD

**Issue by Jing1818** [hollisho/webman-request#1]
TypeError: filter_var(): Argument #3 ($options) must be of type array|int, null given in /app/vendor/topthink/think-validate/src/Validate.php:982

**Comment by hollisho** [comment]
方便贴一下具体Request类中代码吗？

**Comment by hollisho** [comment]
验证规则不用integer，改成number。demo中写法有误，我修改一下。

**Comment by hollisho** [comment]
具体用法可以查看thinkphp官方文档：https://www.kancloud.cn/manual/thinkphp5_1/360141

**Comment by hollisho** [comment]
现在已经支持php8.0
